button_card_templates: !include testing/templates.yaml

kiosk_mode:
  hide_header: true
  #hide_sidebar: '[[[ !user_is_admin ]]]'
views:
  - !include testing/views/home.yaml
  - !include testing/views/power.yaml
  - !include testing/views/scale.yaml
  - !include testing/views/guest.yaml
  - !include testing/views/calendar.yaml
  - !include testing/views/lights.yaml
  - !include testing/views/climate.yaml
  - !include testing/views/rocky.yaml
  - !include testing/views/remote.yaml
  - !include testing/views/media_lists.yaml
  - !include testing/views/media_search_results.yaml